# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datanode.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tanode.proto\x12\x08\x64\x61tanode\"7\n\x14ReplicateDataRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"?\n\x15ReplicateDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"<\n\x15NotifyNameNodeRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x10\n\x08replicas\x18\x02 \x01(\x05\"@\n\x16NotifyNameNodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"$\n\x0fReadFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"H\n\x10ReadFileResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2\xfb\x01\n\x0f\x44\x61taNodeService\x12P\n\rReplicateData\x12\x1e.datanode.ReplicateDataRequest\x1a\x1f.datanode.ReplicateDataResponse\x12S\n\x0eNotifyNameNode\x12\x1f.datanode.NotifyNameNodeRequest\x1a .datanode.NotifyNameNodeResponse\x12\x41\n\x08ReadFile\x12\x19.datanode.ReadFileRequest\x1a\x1a.datanode.ReadFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datanode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REPLICATEDATAREQUEST']._serialized_start=28
  _globals['_REPLICATEDATAREQUEST']._serialized_end=83
  _globals['_REPLICATEDATARESPONSE']._serialized_start=85
  _globals['_REPLICATEDATARESPONSE']._serialized_end=148
  _globals['_NOTIFYNAMENODEREQUEST']._serialized_start=150
  _globals['_NOTIFYNAMENODEREQUEST']._serialized_end=210
  _globals['_NOTIFYNAMENODERESPONSE']._serialized_start=212
  _globals['_NOTIFYNAMENODERESPONSE']._serialized_end=276
  _globals['_READFILEREQUEST']._serialized_start=278
  _globals['_READFILEREQUEST']._serialized_end=314
  _globals['_READFILERESPONSE']._serialized_start=316
  _globals['_READFILERESPONSE']._serialized_end=388
  _globals['_DATANODESERVICE']._serialized_start=391
  _globals['_DATANODESERVICE']._serialized_end=642
# @@protoc_insertion_point(module_scope)
