# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66iles.proto\x12\x0e\x66ilemanagement\"0\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"0\n\x0c\x46ileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"E\n\x10ListFilesRequest\x12\x12\n\nnameFilter\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"&\n\x11ListFilesResponse\x12\x11\n\tfilenames\x18\x01 \x03(\t\"+\n\x17\x46ileNotificationRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"<\n\x18\x46ileNotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"7\n\x14ReplicateFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\r\n\x05ports\x18\x02 \x03(\x05\x32\xd8\x03\n\x0b\x46ileManager\x12\x45\n\x08SendFile\x12\x1b.filemanagement.FileRequest\x1a\x1c.filemanagement.FileResponse\x12P\n\tListFiles\x12 .filemanagement.ListFilesRequest\x1a!.filemanagement.ListFilesResponse\x12j\n\x15\x46ileSavedNotification\x12\'.filemanagement.FileNotificationRequest\x1a(.filemanagement.FileNotificationResponse\x12o\n\x1a\x46ileReplicatedNotification\x12\'.filemanagement.FileNotificationRequest\x1a(.filemanagement.FileNotificationResponse\x12S\n\rReplicateFile\x12$.filemanagement.ReplicateFileRequest\x1a\x1c.filemanagement.FileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'files_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEREQUEST']._serialized_start=31
  _globals['_FILEREQUEST']._serialized_end=79
  _globals['_FILERESPONSE']._serialized_start=81
  _globals['_FILERESPONSE']._serialized_end=129
  _globals['_LISTFILESREQUEST']._serialized_start=131
  _globals['_LISTFILESREQUEST']._serialized_end=200
  _globals['_LISTFILESRESPONSE']._serialized_start=202
  _globals['_LISTFILESRESPONSE']._serialized_end=240
  _globals['_FILENOTIFICATIONREQUEST']._serialized_start=242
  _globals['_FILENOTIFICATIONREQUEST']._serialized_end=285
  _globals['_FILENOTIFICATIONRESPONSE']._serialized_start=287
  _globals['_FILENOTIFICATIONRESPONSE']._serialized_end=347
  _globals['_REPLICATEFILEREQUEST']._serialized_start=349
  _globals['_REPLICATEFILEREQUEST']._serialized_end=404
  _globals['_FILEMANAGER']._serialized_start=407
  _globals['_FILEMANAGER']._serialized_end=879
# @@protoc_insertion_point(module_scope)
