# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namenode.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enamenode.proto\x12\x08namenode\"<\n\x19SendFileToDataNodeRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"D\n\x1aSendFileToDataNodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"H\n\"ReceiveResponseFromDataNodeRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"R\n#ReceiveResponseFromDataNodeResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x15\n\x13\x46ileRegistryRequest\"b\n\x14\x46ileRegistryResponse\x12\"\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x13.namenode.FileEntry\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"6\n\tFileEntry\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x16\n\x0enode_addresses\x18\x02 \x03(\t2\xc0\x02\n\x0fNameNodeService\x12_\n\x12SendFileToDataNode\x12#.namenode.SendFileToDataNodeRequest\x1a$.namenode.SendFileToDataNodeResponse\x12z\n\x1bReceiveResponseFromDataNode\x12,.namenode.ReceiveResponseFromDataNodeRequest\x1a-.namenode.ReceiveResponseFromDataNodeResponse\x12P\n\x0fGetFileRegistry\x12\x1d.namenode.FileRegistryRequest\x1a\x1e.namenode.FileRegistryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'namenode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENDFILETODATANODEREQUEST']._serialized_start=28
  _globals['_SENDFILETODATANODEREQUEST']._serialized_end=88
  _globals['_SENDFILETODATANODERESPONSE']._serialized_start=90
  _globals['_SENDFILETODATANODERESPONSE']._serialized_end=158
  _globals['_RECEIVERESPONSEFROMDATANODEREQUEST']._serialized_start=160
  _globals['_RECEIVERESPONSEFROMDATANODEREQUEST']._serialized_end=232
  _globals['_RECEIVERESPONSEFROMDATANODERESPONSE']._serialized_start=234
  _globals['_RECEIVERESPONSEFROMDATANODERESPONSE']._serialized_end=316
  _globals['_FILEREGISTRYREQUEST']._serialized_start=318
  _globals['_FILEREGISTRYREQUEST']._serialized_end=339
  _globals['_FILEREGISTRYRESPONSE']._serialized_start=341
  _globals['_FILEREGISTRYRESPONSE']._serialized_end=439
  _globals['_FILEENTRY']._serialized_start=441
  _globals['_FILEENTRY']._serialized_end=495
  _globals['_NAMENODESERVICE']._serialized_start=498
  _globals['_NAMENODESERVICE']._serialized_end=818
# @@protoc_insertion_point(module_scope)
